<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="98" started-at="2017-04-25T01:14:34Z" finished-at="2017-04-25T01:14:34Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="98" started-at="2017-04-25T01:14:34Z" finished-at="2017-04-25T01:14:34Z">
      <class name="com.testng.com.NewTest">
        <test-method status="PASS" signature="f()[pri:0, instance:com.testng.com.NewTest@367cca66]" name="f" duration-ms="27" started-at="2017-04-25T06:44:34Z" finished-at="2017-04-25T06:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- f -->
        <test-method status="PASS" signature="testCaseConditionalSkipException()[pri:0, instance:com.testng.com.NewTest@367cca66]" name="testCaseConditionalSkipException" duration-ms="5" started-at="2017-04-25T06:44:34Z" finished-at="2017-04-25T06:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseConditionalSkipException -->
        <test-method status="SKIP" signature="testCaseSkipException()[pri:0, instance:com.testng.com.NewTest@367cca66]" name="testCaseSkipException" duration-ms="8" started-at="2017-04-25T06:44:34Z" finished-at="2017-04-25T06:44:34Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping this exception]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping this exception
	at com.testng.com.NewTest.testCaseSkipException(NewTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCaseSkipException -->
      </class> <!-- com.testng.com.NewTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
